version: "3.9"

services:
  database:
    image: postgres
    container_name: container-bd-tasks
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=carlos
      - POSTGRES_PASSWORD=stbarbara2025
      - POSTGRES_DB=bd-tasks
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local